# Generated by Django 3.0.8 on 2020-11-16 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buckets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipe',
            name='statement_text',
            field=models.CharField(default='Text', max_length=200),
        ),
    ]
