# Generated by Django 3.0.8 on 2020-11-16 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buckets', '0002_pipe_statement_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pipe',
            old_name='bucket',
            new_name='bucket_id',
        ),
        migrations.RenameField(
            model_name='pipe',
            old_name='destination',
            new_name='destination_id',
        ),
    ]
