# Generated by Django 3.0.8 on 2020-11-16 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buckets', '0003_auto_20201116_2138'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pipe',
            old_name='bucket_id',
            new_name='bucket',
        ),
        migrations.RenameField(
            model_name='pipe',
            old_name='destination_id',
            new_name='destination',
        ),
    ]
